#!/usr/bin/env bash

# Added Laravel Init Commands
cd /var/www/html \
    && composer install --optimize-autoloader --no-dev \
    && php artisan key:generate \
    && php artisan optimize \
    && php artisan route:clear &

exec "$@"
